name: ai4beg
channels:
  - defaults
  - microsoft
dependencies:
  - python=3.10  # Örnek: Python 3.9 kullanıyoruz, siz istediğiniz sürümü yazabilirsiniz
  - openai
  - python-dotenv
  - pip
  - pip:
      - azure-ai-ml